import { appendFileSync, mkdtempSync, readFileSync, writeFileSync } from "node:fs";
import { dirname, join, resolve } from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";

const repositoryRoot = resolve(dirname(fileURLToPath(import.meta.url)), "..");
const requiredSecrets = [
  "ANDROID_KEYSTORE_BASE64",
  "ANDROID_KEY_ALIAS",
  "ANDROID_KEY_PASSWORD",
  "ANDROID_STORE_PASSWORD",
];

// Read secrets at Gradle execution time: passwords never become generated source.
const signingConfig = `
// Telegram Star release signing; generated by scripts/android-signing.mjs.
android {
    signingConfigs {
        create("telegramStarRelease") {
            storeFile = file(requireNotNull(System.getenv("ANDROID_KEYSTORE_PATH")))
            storePassword = requireNotNull(System.getenv("ANDROID_STORE_PASSWORD"))
            keyAlias = requireNotNull(System.getenv("ANDROID_KEY_ALIAS"))
            keyPassword = requireNotNull(System.getenv("ANDROID_KEY_PASSWORD"))
        }
    }
    buildTypes {
        getByName("release") {
            signingConfig = signingConfigs.getByName("telegramStarRelease")
        }
    }
}
`;

export function validateSigningSecrets(env = process.env) {
  const missing = requiredSecrets.filter((name) => !env[name]?.trim());
  if (missing.length) {
    throw new Error(`Android release signing is enabled but secrets are missing: ${missing.join(", ")}`);
  }

  // Buffer.from is permissive; round-trip validation rejects corrupted secret values.
  const encoded = env.ANDROID_KEYSTORE_BASE64.replace(/\s/g, "");
  const keystore = Buffer.from(encoded, "base64");
  if (!keystore.length || keystore.toString("base64") !== encoded) {
    throw new Error("ANDROID_KEYSTORE_BASE64 must contain the complete base64-encoded keystore.");
  }
  return keystore;
}

export function prepareAndroidSigning({
  env = process.env,
  androidProjectDir = join(repositoryRoot, "packages/mobile/src-tauri/gen/android"),
} = {}) {
  const keystore = validateSigningSecrets(env);
  if (!env.RUNNER_TEMP || !env.GITHUB_ENV) {
    throw new Error("Android signing setup requires RUNNER_TEMP and GITHUB_ENV from GitHub Actions.");
  }

  const gradlePath = join(androidProjectDir, "app/build.gradle.kts");
  const source = readFileSync(gradlePath, "utf8");
  if (!source.includes('getByName("release")')) {
    throw new Error("Android app Gradle release configuration was not found; run cargo tauri android init first.");
  }
  if (source.includes('create("telegramStarRelease")') && !source.includes(signingConfig)) {
    throw new Error("An unexpected Telegram Star signing configuration already exists.");
  }

  const signingDirectory = mkdtempSync(join(env.RUNNER_TEMP, "telegram-star-android-signing-"));
  const keystorePath = join(signingDirectory, "release.jks");
  if (/[\r\n]/.test(keystorePath)) {
    throw new Error("The runner signing directory must not contain line breaks.");
  }
  writeFileSync(keystorePath, keystore, { mode: 0o600 });
  appendFileSync(env.GITHUB_ENV, `ANDROID_KEYSTORE_PATH=${keystorePath}\n`);

  // A second android block configures the same extension without editing template internals.
  if (!source.includes(signingConfig)) {
    writeFileSync(gradlePath, source.trimEnd() + "\n" + signingConfig);
  }
  return keystorePath;
}

if (process.argv[1] && import.meta.url === pathToFileURL(resolve(process.argv[1])).href) {
  try {
    if (process.argv[2] === "--check") {
      validateSigningSecrets();
      console.log("Android release signing secrets are present.");
    } else if (process.argv.length === 2) {
      prepareAndroidSigning();
      console.log("Android release signing is configured using the runner's temporary keystore.");
    } else {
      throw new Error("Usage: node scripts/android-signing.mjs [--check]");
    }
  } catch (error) {
    console.error(error.message);
    process.exitCode = 1;
  }
}
